# Generated by Django 4.1.4 on 2022-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="shift",
            field=models.CharField(
                choices=[("MATUTINO", "Morning"), ("Não informado", "Default")],
                default="Não informado",
                max_length=50,
                null=True,
            ),
        ),
    ]
