# Generated by Django 4.1.4 on 2022-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="shift",
            field=models.CharField(
                choices=[
                    ("MATUTINO", "Morning"),
                    ("Noturno", "Night"),
                    ("Vespertino", "Afternon"),
                    ("Não informado", "Default"),
                ],
                default="Não informado",
                max_length=50,
                null=True,
            ),
        ),
    ]
