# Generated by Django 4.1.4 on 2022-12-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("floors", "0002_spot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=10)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Car"), ("motorcycle", "Motorcycle")],
                        max_length=20,
                    ),
                ),
                ("arrived_at", models.DateTimeField(auto_now_add=True)),
                ("amount_paid", models.IntegerField(default=None, null=True)),
                ("paid_at", models.DateTimeField(default=None, null=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="floors.spot",
                    ),
                ),
            ],
        ),
    ]
