# Generated by Django 4.1.4 on 2022-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("floors", "0002_spot"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
